local({pkg <- select.list(sort(.packages(all.available = TRUE)),graphics=TRUE)
+ if(nchar(pkg)) library(pkg, character.only=TRUE)})
setwd("C:/Users/shafim/Desktop/Spring 2019/Stat 451/Project")
Sales<-read.csv("Total_retail.csv")
sales.ts<-ts(Sales,freq=12,start=1992)
sales.tsd<-tsd(sales.ts,data.title="Total Retail Sales in the US",time.units="Year",response.units="Thousands of Dollars")
iden(sales.tsd)
iden(sales.tsd,gamma=.5)
iden(sales.tsd, gamma=.5, d=1)
iden(sales.tsd, gamma=.5, D=1)
iden(sales.tsd, gamma=.5, d=1,D=1)
#SARIMA(3,0,0),(1,1,0)
esti(data.tsd=sales.tsd,model=model.pdq(p=3,P=1,D=1),print.table=TRUE,gamma=.5)
#SARIMA(1,1,1),(1,0,1)
esti(data.tsd=sales.tsd,model=model.pdq(p=1,d=1,q=1,P=1,Q=1),print.table=TRUE,gamma=.5)
#SARIMA(1,1,1),(1,1,1)
esti(data.tsd=sales.tsd,model=model.pdq(p=1,d=1,q=1,P=1,D=1,Q=1),print.table=TRUE,gamma=.5)
#SARIMA(2,1,2),(2,1,2)
esti(data.tsd=sales.tsd,model=model.pdq(p=2,d=1,q=2,P=2,D=1,Q=2),print.table=TRUE,gamma=.5)
#SARIMA(2,1,1),(2,1,2)
esti(data.tsd=sales.tsd,model=model.pdq(p=2,d=1,q=1,P=2,D=1,Q=2),print.table=TRUE,gamma=.5)
