local({pkg <- select.list(sort(.packages(all.available = TRUE)),graphics=TRUE)
+ if(nchar(pkg)) library(pkg, character.only=TRUE)})
setwd("C:/Users/shafim/Desktop/Spring 2019/Stat 451/Project")
SAT<-read.csv("SAT.csv")
SAT<-read.csv("SAT.csv")
sat.ts<-ts(SAT, start=1972)
sat.tsd<-tsd(sat.ts, data.title="Math Scores on SAT", time.units="Year", response.units="Average Score on Math Portion of SAT")
iden(sat.tsd)
iden(sat.tsd,d=1)
#ARIMA(2,1,0)
esti(data.tsd=sat.tsd,model=model.pdq(p=2,d=1,q=0),print.table=TRUE)
#AR(1)
esti(data.tsd=sat.tsd,model=model.pdq(p=1),print.table=TRUE)
#AR(3)
esti(data.tsd=sat.tsd,model=model.pdq(p=3),print.table=TRUE)
#ARMA(1,1)
esti(data.tsd=sat.tsd,model=model.pdq(p=1,q=1),print.table=TRUE)
#ARMA(2,1)
esti(data.tsd=sat.tsd,model=model.pdq(p=2,q=1),print.table=TRUE)
dump("sat.tsd","sat.tsd.R")
